markdown: kramdown
permalink: /:year/:month/:title/
relative_permalinks: false

paginate: 5
paginate_path: "page-:num"

title: Eric's Devblog
description: Developer blog for Eric Oestrich
url: http://blog.oestrich.org

keep_files:
  - images
  - img

exclude:
  - Gemfile
  - Gemfile.lock
  - build
  - vendor

plugins:
  - jekyll-paginate
